#!/bin/bash
# This script will create an exectuable jar file for the java portion of the THetA code 

echo "Removing previous builds"
rm -rf bin
mkdir bin

echo "Installing RunTHetA..."
cp python/RunTHetA bin

echo "Installing BICSeqToTHetA..."
ant

echo "Installing CreateExomeInput..."
cp python/CreateExomeInput bin

echo "Installation complete.  Check for errors."
